name: PolicyGPT Local
values:
  - key: baseUrl
    value: 'http://localhost:8000'
    enabled: true
    type: default
  - key: apiV1
    value: '/api/v1'
    enabled: true
    type: default
  - key: authToken
    value: ''
    enabled: true
    type: default
  - key: policyId
    value: '1'
    enabled: true
    type: default
  - key: schemeId
    value: '1'
    enabled: true
    type: default
  - key: feedbackId
    value: '1'
    enabled: true
    type: default
  - key: faqId
    value: '1'
    enabled: true
    type: default
  - key: resetToken
    value: ''
    enabled: true
    type: default
