const fs = require('fs');
const path = require('path');

const targetPath = path.join(__dirname, '../src/environments/environment.prod.ts');
const devPath = path.join(__dirname, '../src/environments/environment.development.ts');

// Check environment variables provided at build time (e.g. on Netlify / Vercel / CI)
const apiUrl = process.env.API_URL || process.env.VITE_API_URL || process.env.NG_APP_API_URL || process.env.BACKEND_URL || '';

let formattedApiUrl = apiUrl.trim();
if (formattedApiUrl && !formattedApiUrl.endsWith('/api/v1')) {
  formattedApiUrl = formattedApiUrl.replace(/\/+$/, '') + '/api/v1';
}

console.log(`[build-env] Configuring production environment with API_URL: "${formattedApiUrl || '(not provided, using fallback/empty)'}"`);

const envFileContent = `// Auto-generated by scripts/set-env.js at build time
export const environment = {
  production: true,
  apiUrl: '${formattedApiUrl}'
};
`;

fs.writeFileSync(targetPath, envFileContent, { encoding: 'utf8' });
console.log(`[build-env] Successfully wrote ${targetPath}`);
